[build]
builder = "DOCKERFILE"
dockerfilePath = "VetCareSV/Dockerfile"
buildContext = "VetCareSV"

[deploy]
startCommand = "dotnet VetCareSV.dll"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
